Lock down versions to working ones
With newer versions of Cucumber we get

> undefined method `feature' for #<Cucumber::Core::Test::Case:
> features/encoding.feature:3> (NoMethodError)
> ~/gems/ruby-3.0.2/gems/fivemat-1.3.7/lib/fivemat/cucumber3.rb:9:in
> `on_test_case_started'

when running

    $ bundle exec cucumber --color --tags 'not @wip' --strict --format Fivemat

seemingly because Fivemat doesn't support Cucumber 4 yet.